name: Rust CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: Build
      run: make rust_build
    - name: Run
      run: make rust_run
    - name: Test
      run: make rust_test
    - name: Format
      run: make rust_format
    - name: Lint
      run: make rust_lint
    - name: Archive Binary
      uses: actions/upload-artifact@v3
      with:
        name: optimized-binary
        path: target/release/Individual_Proj2_Fuyao_Li.exe
    - name: add rust logs
      run: make generate_and_push